version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - "80:8000"
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres:5432
      postgres_user: graph-node
      postgres_pass: ${POSTGRES_PASSWORD}
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "${NETWORK}:${ETHEREUM_RPC}"
      RUST_LOG: error
      GRAPH_LOG: info
      ETHEREUM_ANCESTOR_COUNT: 0
      ETHEREUM_REORG_THRESHOLD: 0
    restart: always
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - "5001:5001"
      - "8030:8030"
    volumes:
      - ./data/ipfs:/data/ipfs
    restart: always
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  graph-deployer:
    build: ../
    depends_on:
      - graph-node
      - postgres
    environment:
      - GRAPH_ADMIN_RPC_URL=http://graph-node:8020/
      - IPFS_URL=http://ipfs:5001
      - SUBGRAPH_NAME=reflexer-labs/rai
      - NETWORK
    command: './docker/wait-for-it.sh\ graph-node:8000\ --timeout=40\ &&\ npm\ run\ deploy-local'
